const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const foodSchema = new Schema({
  name: { type: String, required: true },
  weight: { type: String, required: true },
  energy: { type: Number, required: true },
  protein: { type: Number },
  carbs: { type: Number },
  fat: { type: Number },

  FoodGroup: { type: String, default: "" },
  Description: { type: String, default: "" },
  CommonName: { type: String, default: "" },
  MfgName: { type: String, default: "" },
  ScientificName: { type: String, default: "" },
  Energy_kcal: { type: String, default: "" },
  Protein_g: { type: String, default: "" },
  Fat_g: { type: String, default: "" },
  Carb_g: { type: String, default: "" },
  Sugar_g: { type: String, default: "" },
  Fiber_g: { type: String, default: "" },
  VitA_mcg: { type: String, default: "" },
  VitB6_mg: { type: String, default: "" },
  VitB12_mcg: { type: String, default: "" },
  VitC_mg: { type: String, default: "" },
  VitE_mg: { type: String, default: "" },
  Folate_mcg: { type: String, default: "" },
  Niacin_mg: { type: String, default: "" },
  Riboflavin_mg: { type: String, default: "" },
  Thiamin_mg: { type: String, default: "" },
  Calcium_mg: { type: String, default: "" },
  Copper_mcg: { type: String, default: "" },
  Iron_mg: { type: String, default: "" },
  Magnesium_mg: { type: String, default: "" },
  Manganese_mg: { type: String, default: "" },
  Phosphorus_mg: { type: String, default: "" },
  Selenium_mcg: { type: String, default: "" },
  Zinc_mg: { type: String, default: "" },
  VitA_USRDA: { type: String, default: "" },
  VitB6_USRDA: { type: String, default: "" },
  VitB12_USRDA: { type: String, default: "" },
  VitC_USRDA: { type: String, default: "" },
  VitE_USRDA: { type: String, default: "" },
  Folate_USRDA: { type: String, default: "" },
  Niacin_USRDA: { type: String, default: "" },
  Riboflavin_USRDA: { type: String, default: "" },
  Thiamin_USRDA: { type: String, default: "" },
  Calcium_USRDA: { type: String, default: "" },
  Copper_USRDA: { type: String, default: "" },
  Magnesium_USRDA: { type: String, default: "" },
  Phosphorus_USRDA: { type: String, default: "" },
  Selenium_USRDA: { type: String, default: "" },
  Zinc_USRDA: { type: String, default: "" },
});

const Food = mongoose.model("Food", foodSchema);
module.exports = Food;
